### ISSUE TITLE
Please refer to a "warning" (actually just a PM that I didn't want you miss) on mopar. Thanks. - Jc

### ISSUE THREAD

**Issue by sean-niemann** [hikilaka/rscemulation#5]
^

**Comment by sean-niemann** [comment]
Dustin has asked me to reach out to you, if you are wondering.

**Comment by hikilaka** [comment]
Cool. Like I care if my post on broken forum gets deleted. Good luck censoring me.

**Comment by sean-niemann** [comment]
Whatever. Not worth my time; didn't even realize the site got abandoned. Hadn't been on in years. Also, if I had to throw some positivity your way, it would be this:

You've shown signs over the years that you actually are pretty decent as as software developer. You could do a lot more important things in life with your knowledge than messing around with a 17 year old JDK 1.1 compatible game. Why don't you? Learn from this guy https://github.com/reines. You've probably heard of him, lol. And if you think I'm still messing around with the RSC scene, you're mistaken. I just check in with the community every few months or so.

Don't think of this reply as bare criticism; but rather constructive criticism.
